databases:
  - name: the-wall
    plan: free
    databaseName: the-wall
    user: postgres

services:
  - type: web
    plan: free
    name: the-wall
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn wall.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the-wall
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4