# Generated by Django 5.0.6 on 2024-06-22 13:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_vote_unique_vote_and_post_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='each user can vote each post just once',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='each user can vote each comment just once',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('author', 'post'), name='each user can vote each post just once', violation_error_message='Already voted on this post'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='each user can vote each comment just once', violation_error_message='Already voted on this comment'),
        ),
    ]
